require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - "*.gemspec"

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4
